### ISSUE TITLE
@font-face CORS support

### ISSUE THREAD

**Issue by seanakabry** [standardnotes/listed#11]
Does Listed prohibit pulling typefaces from other domains using CSS's `@font-face`, and if so, is this a security feature?

I assume so based on [this SO answer](https://stackoverflow.com/questions/21049629/html5-web-font-security/21049765#21049765), but would like to be sure that I'm not doing something else incorrectly. If the problem was with the server hosting the typeface, I'd expect to see 403 errors in the browser console, but don't.

**Comment by atmoio** [comment]
I don't think we disallow this.

**Comment by seanakabry** [comment]
Apologies. A `@font-face` test page I set up appeared to work, but now that I've flushed my browser cache, I see that it doesn't—so this is an issue with my server, not Listed.

**Comment by seanakabry** [comment]
The issue seems to be that Listed omits declarations in the `@font-face` block beginning with `src:`, which are missing when I view source on my blog.

I fixed the relevant Apache declaration on the server hosting the typeface, and confirmed that I could use the typeface on a third domain.

Test page:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>@font-face Test</title>
  <style type="text/css">

    @font-face {
      font-family: GentiumPlus;
      src: local("GentiumPlus-R.ttf") format("ttf");
      src: url("https://path/to/GentiumPlus-R.woff") format("woff");
      font-weight: 400;
      font-style: normal;
    }

    @font-face {
      font-family: GentiumPlus;
      src: local("GentiumPlus-I.ttf") format("ttf");
      src: url("https://path/to/GentiumPlus-I.woff") format("woff");
      font-weight: 400;
      font-style: italic;
    }

    * {
      font-family: GentiumPlus;
    }

  </style>
</head>
<body>

  <h1>Hello World!</h1>

</body>
</html>
```

Temporary `.htaccess` in the directory hosting the typeface:

```
<FilesMatch "\.(ttf|otf|eot|woff|woff2)$">
  <IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin *
  </IfModule>
</FilesMatch>
```

**Comment by atmoio** [comment]
This blog uses a custom font, I'd take a look at how they do it: https://listed.to/@jon

**Comment by seanakabry** [comment]
Many thanks. This worked:

In the Listed blog's CSS:

```css
@import url("https://path/to/gentium.css");
```

In `gentium.css`, in the same directory as the hosted typefaces:

```css
@font-face {
  font-family: GentiumPlus;
  src: local("GentiumPlus-R.ttf") format("ttf");
  src: url("GentiumPlus-R.woff") format("woff");
  font-weight: 400;
  font-style: normal;
}

@font-face {
  font-family: GentiumPlus;
  src: local("GentiumPlus-I.ttf") format("ttf");
  src: url("GentiumPlus-I.woff") format("woff");
  font-weight: 400;
  font-style: italic;
}
```
