### ISSUE TITLE
Rendering of custom font

### ISSUE THREAD

**Issue by cr7yash** [standardnotes/listed#117]
![Screenshot from 2021-02-18 13-15-40](https://user-images.githubusercontent.com/15312466/108322589-a84ffe00-71eb-11eb-9490-7ca6b36567d4.png)

Hi! I am trying to override the font styles but it doesn't render when I publish the themes.css file and refresh my blog page. Any help would be greatly appreciated :)

Ps. I am using brave browser and I also tried with shields down, didn't help.

**Comment by JaspalSuri** [comment]
Hi @cr7yash,

These fonts will only load if you have them installed on your OS. It appears that they are provided by [Google](https://fonts.google.com/) but since there isn't a way to import them, they will not render automatically on your blog. 

[Here is a list of fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp) that are supported across multiple platforms.

**Comment by cr7yash** [comment]
Yes, I think not  able to import these fonts solves the issue. Thanks for the help!

**Comment by JaspalSuri** [comment]
You're welcome! Please let us know if you have any other questions in the future. 🙂

**Comment by JaspalSuri** [comment]
Hi @cr7yash, I want to apologize for not having the correct information on hand earlier. You can import and apply a font from Google (or another font hosting provider). [Here is an example](https://docs.standardnotes.org/listed/styles/#custom-fonts) of how it could look like based on the CSS you've provided above.

```CSS
/* Import the font */
@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');

/* Declare the font family */
.post-title, .h1 {
  font-family: Merriweather, serif;
}
.post-body, body {
  font-family: 'Inter', Roboto, sans-serif;
}
```

The _Meriweather_ font is imported by Listed by default, so you should be able to use it without explicitly importing. 🙂
