### ISSUE TITLE
Mobile logo for improved readability

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/listed#159]
The Listed L logo may need to have an improved or enlarged version for Mobile for readability at small sizes as the thin part of the font almost disappears when viewing on mobile.![image](https://user-images.githubusercontent.com/62911518/114161383-fcc35000-98f5-11eb-96ba-9f269178e6b6.jpeg)

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, thanks for the feedback! If we continue to receive more reports of this issue we'll consider changing it. 🙂

**Comment by lissy93** [comment]
Also with the logo, I have found that when using a custom color (just using the variable), I get an unusual intro animation on initial page load. E.g.
[![screen recording](https://i.ibb.co/BGFbyCs/listed-logo-unusual-intro-animation.gif)](https://listed.to/@lissy93/)

For reference, it's caused by the following code in [`application.scss`](https://github.com/standardnotes/listed/blob/develop/client/app/assets/styles/application.scss#L227)
```css
.button--no-fill:before {
	background-image: linear-gradient(0deg,var(--page-menu-link-color) 50%,transparent 0);
	background-size: 100% 200%;
	background-position: top;
	transition: background-position .3s ease-in-out;
}
```
Not a major issue by any stretch, but would be nice for the above code to be simplified to avoid this.
