### ISSUE TITLE
RFE:  Dark Mode

### ISSUE THREAD

**Issue by kfiresmith** [standardnotes/listed#82]
It's jarring to work in midnight/futura within Standard Notes then to see what is published in retina burning snowstorm white.
It would be nice to be able to set some presets across a whole Listed account related to UI, even if it's just a binary toggle between a dark and light CSS.

**Comment by JaspalSuri** [comment]
Hi @kfiresmith,

While this isn't quite what you're looking for, you can customize the style of your blog by creating a special type of post with styling rules for your blog via CSS. Please [see this support article](https://docs.standardnotes.org/listed/styles) for more information. 

If you come across another Listed blog whose style you would like to copy (and/or modify), you can right-click the page of that blog, click **View Page Source** in the context menu, and view the CSS used; it's located at the top of the page.

**Comment by kfiresmith** [comment]
Hi @JaspalSuri  - thank you for the reply.  That's sort of a hard sell for casual users like me.  
I did notice that even the Standard Notes documentation site you linked has a quick day/night mode toggle which is sort of funny in the context of this discussion.  

Seems like it would be an easy bolt-on to carry that over from the doc site to the listed.to site... :)

**Comment by kfiresmith** [comment]
Do you know what CSS value dictates background color for code blocks in markdown?  I was able to steal someone else's darkish-mode CSS but lost my contrasting code block background.  Example:  https://listed.to/@kodiak/20288/netapp-add-network-conns

**Comment by atmoio** [comment]
Best way to find out would just be to right click on a rendered code block, Inspect Element, then fiddle around with interactive CSS editor to see what property you'd need to edit to get the desired result. Some leads might be `pre`, `code`, and `background-color`.

**Comment by kfiresmith** [comment]
I appreciate this advice, and for myself I will try to do that.  I do want to hopefully make clear that this would be intimidating advice for paying customers who are not in the field of tech, or like me, may be backend guys who try to stay a million miles from front-end stuff like CSS.  

I think the topic is exhausted at this point so I'll close the issue, but I do hope that the Standard Notes / Listed staff on the board are thinking about how to make future versions a bit more user-friendly on this front.

Thanks again everyone!

**Comment by JaspalSuri** [comment]
Hi @kfiresmith,

@TheodoreChu created a theme for [Listed](https://listed.to) (based on [Midnight](https://standardnotes.org/extensions/midnight)) that follow's the user's light and dark mode preferences. You can add the following to your custom CSS. 

```CSS
@media (prefers-color-scheme: dark) {
  :root {
  --background-color: #20202b; /* background color */
  --body-text-color: #d8d8d8; /* foreground color */
  }
  .post-content table th, .post-content table td {
    border: 1px solid #13131a;
    color: var(--body-text-color);
  }
  .post-content table tr:nth-child(1n) {
    background-color: var(--background-color);
  }
  .post-content table tr:nth-child(2n) {
    background-color: #313142; /* contrast background color */
  }
  .post-content table tr:nth-child(2n) td code {
    background-color: var(--background-color);
  }
  pre, code, .post-content pre, .post-content p code, .post-content .highlight {
    background-color: #313142; /* contrast background color */
    border: 0px;
    color: var(--body-text-color);
  }   
}
```

That said, this wouldn't affect other Listed blogs unless you used something like the [Stylus extension](https://github.com/openstyles/stylus) for a desktop web browser like Firefox or a variant of Google Chrome.
